# workflow name
name: Basic workflow

#workflow trigger
on: workflow_dispatch
    #push:
       # branches:
      #      - main
 
# jobs
jobs:
    build:
      name: Build and Test
      runs-on: ubuntu-latest #runner
    
      steps: #steps
       - name: checkout code
         uses: actions/checkout@v4
       
         
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
          node-version: "20"

       - name: Install deps
         run: npm install

       - name: Run tests
         run: npm test  

       - name: Print
         run: echo "Everything Succesfull" 
