name: caching deps

on: workflow_dispatch

jobs:
    build-with-cache:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Setup node js
            uses: actions/setup-node@v4
            with:
               node-version: "20"

               cache: "npm"

          - name: Install deps
            run: npm install

          - name: Cache build
            uses: actions/cache@v3
            with:
               path: |
                dist/
                build/
                .next/cache    

               key:  ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

               restore-keys: |
                ${{ runner.os }}-build-
                ${{ runner.os }}-

           
          - name: Build
            run: npm run build            